import type { Project } from "./types";

export const SEED_PROJECTS: Project[] = [
  {
    id: "prj-01",
    name: "Rural School Infrastructure",
    partner: "HL Foundation Trust",
    sector: "Education",
    sanctionedAmount: 1850000,
    spentAmount: 1332000,
    currentStage: "implementation",
    startDate: "2025-08-01",
    plannedEndDate: "2026-02-28",
    pace: 55,
    workDone: 62,
    risk: "on-track",
    status: "Active",
  },
  {
    id: "prj-02",
    name: "Drinking Water Tanks",
    partner: "Village Water Collective",
    sector: "Sanitation & Water",
    sanctionedAmount: 1420000,
    spentAmount: 852000,
    currentStage: "implementation",
    startDate: "2025-07-15",
    plannedEndDate: "2026-01-15",
    pace: 72,
    workDone: 60,
    risk: "at-risk",
    status: "Active",
  },
  {
    id: "prj-03",
    name: "Mobile Health Camps",
    partner: "Campus Medical NGO",
    sector: "Healthcare",
    sanctionedAmount: 980000,
    spentAmount: 431200,
    currentStage: "monitoring",
    startDate: "2025-09-01",
    plannedEndDate: "2026-03-31",
    pace: 40,
    workDone: 34,
    risk: "on-track",
    status: "Active",
  },
  {
    id: "prj-04",
    name: "Digital Literacy for Farmers",
    partner: "Agro Resource Center",
    sector: "Livelihood",
    sanctionedAmount: 760000,
    spentAmount: 10200,
    currentStage: "approval",
    startDate: "2026-01-05",
    plannedEndDate: "2026-06-30",
    pace: 12,
    workDone: 5,
    risk: "at-risk",
    status: "Awaiting approval",
  },
  {
    id: "prj-05",
    name: "Skill Centre Phase-1",
    partner: "Youth Uplift Trust",
    sector: "Skill Development",
    sanctionedAmount: 2100000,
    spentAmount: 2058000,
    currentStage: "closure",
    startDate: "2025-02-01",
    plannedEndDate: "2025-12-31",
    pace: 100,
    workDone: 98,
    risk: "on-track",
    status: "Closure in progress",
  },
];

